### PR TITLE
Create react app with typescript.

### PR DESCRIPTION
**Pull request by ShenTom**
Add eslint and prettier config.
- Issue #21

### CODE REVIEW

**Comment by ShenTom** [comment]
Any ideas on why its failing the test? This is should be just a basic create-react-app skeleton code.

**Comment by jurabek** [comment]
@ShenTom yes it is just `create-react-app` empty app, feel free to remove UI component tests

**Comment by ShenTom** [comment]
Looks like the action is asking me to set the SONAR_TOKEN env variable. Is there anything that I need to do on my local machine.

**Comment by jurabek** [comment]
No, locally you need just run docker-compose in server folder, then check it out for example http://localhost:8080/menu/swagger/index.html

**Comment by jurabek** [comment]
@ShenTom if you have any question regarding Backend please let me know,

**Pull request closed without merging**
